// Fill out your copyright notice in the Description page of Project Settings.


#include "ShipScontroller.h"
#include "Components/BoxComponent.h"
#include "Components/InputComponent.h"
#include"BulletController.h"
#include"EnemyController.h"
#include "Kismet/GameplayStatics.h"
#include"SpaceShooterGameMode.h"

// Sets default values
AShipScontroller::AShipScontroller()
{
 	// Set this pawn to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;

	//A box generally used for simple collision. Bounds are rendered as lines in the editor.
	CollisionBox = CreateDefaultSubobject<UBoxComponent>(TEXT("Root"));//este component recebe a string Root
	CollisionBox->SetGenerateOverlapEvents (true);
	CollisionBox->OnComponentBeginOverlap.AddDynamic(this, &AShipScontroller::OnOverlap);

	//Determines which PlayerController, if any, should automatically possess the pawn when the level starts or when the pawn is spawned.
	AutoPossessPlayer = EAutoReceiveInput::Player0;//
}

// Called when the game starts or when spawned
void AShipScontroller::BeginPlay()
{
	Super::BeginPlay();
	CollisionBox->OnComponentBeginOverlap.AddDynamic(this, &AShipScontroller::OnOverlap);

}

// Called every frame
void AShipScontroller::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
	if (!CurrentVelocity.IsZero())//if  velocity is not zero
	{
		FVector NewLocation = GetActorLocation() + Speed * CurrentVelocity
			* DeltaTime;//moves the player
		SetActorLocation(NewLocation);//set the pawn location to the value generated by NewLocation
	}
	

}

// Called to bind functionality to input
void AShipScontroller::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent)
{
	Super::SetupPlayerInputComponent(PlayerInputComponent);
	/
	InputComponent->BindAxis("MoveX",this,&AShipScontroller::Move_XAxis);
	InputComponent->BindAxis("MoveY", this, &AShipScontroller::Move_yAxis);
	InputComponent->BindAction("Shoot", IE_Pressed, this, &AShipScontroller::OnShoot);
	InputComponent->BindAction("Restart", IE_Pressed, this, &AShipScontroller::OnRestart).bExecuteWhenPaused=true;
}

void AShipScontroller::Move_XAxis(float AxisValue)
{
	CurrentVelocity.X = AxisValue * 100.0f;//value used to move the player on the X axis
}

void AShipScontroller::Move_yAxis(float AxisValue)
{
	CurrentVelocity.Y = AxisValue * 100.0f;//value used to move the player on the Y axis
}

void AShipScontroller::OnShoot()
{
	UWorld* World = GetWorld();//Getter for the cached world pointer, will return null if the actor is not actually spawned in a level

	if (World)
	{
		FVector Location = GetActorLocation();
		Location.X += 100;
		//will spawn a bullet 
		World->SpawnActor<ABulletController>(BulletBlueprint, Location, FRotator::ZeroRotator);
	}
}

void AShipScontroller::OnRestart()
{
	//if the player dies and chooses to restart the game this function will restart the game
	if (Died)
	{
		UGameplayStatics::OpenLevel(this, FName(*GetWorld()->GetName()), false);
	}
}

void AShipScontroller::Overlapped()
{
	//when the player is overlapped by and enemy he dies
	Died = true;
	this->SetActorHiddenInGame(true);
	//will call a function that will show the player score
	((ASpaceShooterGameMode*)GetWorld()->GetAuthGameMode())->OnGameOver();
	//pauses the game
	UGameplayStatics::SetGamePaused(GetWorld(), true);
}

void AShipScontroller::OnOverlap(UPrimitiveComponent* OverlappedComponent, AActor* OtherActor, UPrimitiveComponent* OtherComponent, int32 OtherBodyIndex, bool bFromSweep, const FHitResult& SweepResult)
{
	//when the player is overlapped by and enemy he dies
	if (OtherActor->IsA(AEnemyController::StaticClass()))
	{
		Overlapped();
		
	}
}


